---
- hosts: localhost
  remote_user: root
  
  tasks:
   - name : Updating system...
     apt: update_cache=yes
     
   - name : Installing lab pre-requisites...
     apt  : name={{ item }} state=present
     with_items:
      - apache2
      - php5
     environment:
       http_proxy: http://proxy.iiit.ac.in:8080
       https_proxy: http://proxy.iiit.ac.in:8080
   
   - name : Restart services
     shell : service {{ item }} restart
     with_items :
      - apache2

   - name : Running make file
     shell : make -C /root/labs/computer-programming-iiith-ansible/src
   
   - name : Making index.html as default page
     shell : mv /var/www/index.html index.html.default 

   - name : copying build contents to /var/www/
     shell : cp -r /root/labs/computer-programming-iiith-ansible/build/* /var/www/
     
  
  
